apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: peoplefinder-ingress
  namespace: peoplefinder
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: test.service.sci.tu.ac.th
    http:
      paths:
      - path: /
        backend:
          serviceName: peoplefinder-service
          servicePort: 8000
      - path: /static
        backend:
          serviceName: peoplefinder-service
          servicePort: 80
