apiVersion: batch/v1
kind: Job
metadata:
  name: peoplefinder-migrations
spec:
  template:
    spec:
      containers:
        - name: peoplefinder
          image: mastertos/peoplefinder:1
          command: ['python', 'manage.py', 'migrate']
        # command: ['sh', 'run.sh']
          envFrom:
            - secretRef:
              name: peoplefinder-credentials
            - configMapRef:
              name: peoplefinder-configmap
      restartPolicy: Never
  backoffLimit: 5
