kind: Service
apiVersion: v1
metadata:
  name: peoplefinder-service
spec:
  selector:
    app: peoplefinder-container
  ports:
  - name: django
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: nginx
    protocal: TCP
    port: 80
    targetPort: 80
  type: NodePort
