kind: Service
apiVersion: v1
metadata:
  name: peoplefinder-db-service
  namespace: peoplefinder
spec:
  selector:
    app: peoplefinder-db-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
