kind: PersistentVolume
apiVersion: v1
metadata:
  name: peoplefinder-pv
  namespace: peoplefinder
spec:
  capacity:
    storage: 2Gi
  storageClassName: peoplefinder
  accessModes:
    - ReadWriteMany
  nfs:
    path: /
    # FIXME: use the right IP or domain
    server: 10.100.29.191

