kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: peoplefinder-pvc
  namespace: peoplefinder
spec:
  storageClassName: peoplefinder
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: peoplefinder-pv