kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: peoplefinder-pvc
spec:
storageClassName: peoolefinder
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: peoplefinder-pv